### ISSUE TITLE
Performance regression loading dictionary with Python 3.12

### ISSUE THREAD

**Issue by ns-rse** [ilbsm/topoly_tutorial#4]
We use `topoly` in [AFM-SPM/TopoStats](https://github.com/AFM-SPM/TopoStats/) and [discovered](https://github.com/AFM-SPM/TopoStats/issues/927#issuecomment-2388966996) a regression in performance under Python 3.12 when `topoly` loads the dictionary that is contained in `polvalues.py`.

I'm copying over the investigation I made here and have been in contact with @prubach directly about this (via email but also see comments further down in that thread).

We would like TopoStats to support Python 3.12 so anything we can do to help investigate and resolve this matter please let us know.

-----

I've been doing some profiling and have tracked down the cause of this hang to be a module from [Topoly](https://topoly.cent.uw.edu.pl/index.html).

The attached profile was obtained by running...

```bash
git switch 4b7d25813
python -m cProfile -o prof/test_run_filters_cProfile_hangs.prof $(which pytest) tests/test_processing.py::test_run_filters
```

It can then be visualised with the following (you don't have to run the profiling yourself you can just download the attached file and run the following after installing [snakeviz](https://jiffyclub.github.io/snakeviz/)...

```bash
# Optionally install snakeviz
pip install snakeviz
# Uncompress the file
gunzip test_run_filters_cProfile_hangs.prof.gz
# Run snakeviz on the file
snakeviz path/to/test_run_filters_cProfile_hangs.prof
```

A browser tab will open and at the top it shows you that the module where most time is spent is `polyvalues.py`. Only a single call is made to this module...
![image](https://github.com/user-attachments/assets/e7319a85-0416-4a26-912f-c162cb117b46)

The second box from the left (may differ on your view) with no "icicles" is the `polyvalues.py` module and it doesn't actually call or run _any_ processes itself, it just takes a long time to do....something?!?!?!

![image](https://github.com/user-attachments/assets/c66c16d5-397f-4c50-ba7b-fe0a2d50aae2)

[test_run_filters_cProfile_hangs.prof.gz](https://github.com/user-attachments/files/17231504/test_run_filters_cProfile_hangs.prof.gz)

If I repeat this on the previous commit (`git switch 560d0b19d` and repeat the profiling) there is no such problem, no call is made to `polyvalues.py`.

To check I've compared the two commits shows this appears to be the first point at which `topoly` modules are imported, we could use `-G topoly` to search the differences when checked out on the commit that fails and the previous commit  but this exceeds `DFT_GRAPH_LIMIT` so I have gone with pipping it into `grep` (**NB** this is the output from [difftastic](https://difftastic.wilfred.me.uk/) and shows a line has been added to `HEAD` (at line `11`) that isn't in the previous commit (`HEAD~1`), I limit the output to the first 20 lines by piping to `head -n 20`)...

```bash
 ❱ git diff HEAD HEAD~1 | grep topoly -A3 -B3

 ❱ git diff HEAD HEAD~1 | grep topoly -A3 -B3
555- 8  8 import numpy.typing as npt
556- 9  9 import pandas as pd
557-10 10 from skimage.morphology import label
558:11 .. from topoly import jones, translate_code
559-12 11 
560-13 12 from topostats.logs.logs import LOGGER_NAME
561-14 13 from topostats.tracing.tracingfuncs import coord_dist, genTracingFuncs, order_branch, reorderTrace
--
847-349             if len(nxyz) > 2 and end_to_end_dist_square ... 
848-... d <= 2:  # pylint: disable=chained-comparison           ... 
849-350                 # single coord traces mean nxyz[0]==[1] ... 
850:...  so cause issues when duplicating for topoly            ... 
851-351                 nxyz = np.append(nxyz, nxyz[0][np.newax ... 
852-... is, :], axis=0)                                         ... 
853-352             simple_coords.append(nxyz)                  ... 
```

I'm not sure why this is even being called though as I though `topoly` has only been introduced to undertake work in DNA tracing and shouldn't affect the very early stage of `filters`? Certainly none of the files in `topostats/filters.py` have been touched...

```bash
git diff --name-only HEAD HEAD~1
topostats/processing.py
topostats/tracing/ordered_tracing.py
topostats/tracing/splining.py
```

Although perhaps my understanding is wrong and _everything_ is getting initalised for some reason. :thinking: 

@MaxGamill-Sheffield @SylviaWhittle @llwiggins : do you observe this long hang when running the tests? Do you get similar profiling?

**Comment by ns-rse** [comment]
[NumPy v2.2.0](https://numpy.org/devdocs/release/2.2.0-notes.html) was released 2024-12-08. I was wondering if this addresses any of the problems Topoly had encountered with newer NumPy releases @prubach ?

**Comment by prubach** [comment]
> [NumPy v2.2.0](https://numpy.org/devdocs/release/2.2.0-notes.html) was released 2024-12-08. I was wondering if this addresses any of the problems Topoly had encountered with newer NumPy releases @prubach ?

Unfortunately, not. But we started working on that issue.

**Comment by prubach** [comment]
Hi @ns-rse, I just wanted to let you know that we've just released topoly 1.1.0 which finally works with NumPy 2.x and newer Matplotlib versions. Linux/Windows and older Intel Mac packages are available, the ARM Mac and newer Intel Mac will follow a bit later since I don't have these machines at hand.

**Comment by ns-rse** [comment]
@prubach Thanks for the heads up and for the work to fix this that's great to hear, I'll look at testing this in the coming days.

**Comment by ns-rse** [comment]
Tested Topoly-1.1.0 under Python 3.12 and am still seeing this issue. 🤔
